# Generated by Django 6.1.1 on 2026-09-17 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_product_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='text_task',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task',
            new_name='title',
        ),
    ]
